# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:

- bash: |
    export GODOT_VERSION="3.0.6"
    #download godot and templates
    wget --quiet https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip
    wget --quiet https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
    #unpack godot binary
    unzip Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip
    sudo mv Godot_v${GODOT_VERSION}-stable_linux_headless.64 /usr/local/bin/godot
    sudo chmod +x /usr/local/bin/godot
    #create godot cache and config folder
    mkdir -p ~/.config/godot
    mkdir -p ~/.cache
    #create template folder        
    mkdir -p ~/.local/share/godot/templates/${GODOT_VERSION} 
    #unpack templates to the correct folder
    unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz
    mv templates/* ~/.local/share/godot/templates/${GODOT_VERSION}
    #remove temporary files
    rm -f Godot_v${GODOT_VERSION}-stable_export_templates.tpz Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip
  displayName: 'Prepare Godot headless'

- bash: |
    mkdir build
    sudo godot --quit --export "HTML5" --verbose export
  displayName: 'Godot export'

- task: PublishBuildArtifacts@1
    #pathToPublish: $(Build.ArtifactStagingDirectory)
    pathToPublish: $(Build.SourcesDirectory)
    artifactName: 'drop' 
  displayName: "Publish Artifacts"