# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- bash: |
    export GODOT_VERSION="3.0.6"
    wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip
    wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
    unzip Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip
    RUN mv Godot_v${GODOT_VERSION}-stable_linux_headless.64 /usr/local/bin/godot
    unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz
    mkdir -p ~/.local/share/godot/templates/${GODOT_VERSION} 
    mv templates/* ~/.local/share/godot/templates/${GODOT_VERSION}
    rm -f Godot_v${GODOT_VERSION}-stable_export_templates.tpz Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip
  displayName: 'Godot export'
